title: Precision Agriculture
description: Use of IoT in Agriculture
template:
  repo: precision-agriculture-template
  name: precision-agriculture
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
